version: 2.1

jobs:
  run-slither:
    docker:
      - image: cimg/python:3.12.1-node
    steps:
      - checkout
      - run:
          name: Install Slither
          command: |
            python -m pip install --upgrade pip
            pip3 install slither-analyzer
      - run:
          name: Run Slither
          command: |
            # make sure to modify the solidity compiler version
            export SOLC_VERSION=0.4.15
            solc-select install $SOLC_VERSION
            # make sure to modify the path to your contracts
            slither . --sarif slither.sarif --fail-none
      # Make sure you set the `DEEPSOURCE_DSN` env variable as a secret in your project.
      - run:
          name: Upload SARIF report to DeepSource
          command: |
            # Install the DeepSource CLI
            curl https://deepsource.io/cli | sh
            # Send the report to DeepSource
            ./bin/deepsource report --analyzer slither --analyzer-type community --value-file slither.sarif

  run-solhint:
    docker:
      - image: cimg/node:16.20.2
    steps:
      - checkout
      - run:
          name: Install Solhint
          command: |
            npm install solhint@^4.1.1 # version installed should be greater than 4.1.1
      - run:
          name: Run solhint
          command: |
            # make sure to modify the path to your contracts
            npx solhint '*.sol' -f sarif > solhint.sarif || true
      # Make sure you set the `DEEPSOURCE_DSN` env variable as a secret in your project.
      - run:
          name: Upload SARIF report to DeepSource
          command: |
            # Install the DeepSource CLI
            curl https://deepsource.io/cli | sh
            # Send the report to DeepSource
            ./bin/deepsource report --analyzer solhint --analyzer-type community --value-file solhint.sarif

workflows:
  run-slither-solhint-workflow:
    jobs:
      - run-slither
      - run-solhint
